pipeline:
  name: SampleProject
  identifier: SampleProject
  projectIdentifier: pov
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: gsajwan/sample-project
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        template:
          templateRef: cicd_Template
          versionLabel: "1.0"
          gitBranch: main
    - stage:
        name: Deploy
        identifier: Deploy
        tags: {}
        template:
          templateRef: deploy
          versionLabel: "1.0"
          gitBranch: main
